# Site settings
title: Carlos Xavier Hern&aacute;ndez
firstname: Carlos
middlename: Xavier
lastname: Hernández
email: cxh@stanford.edu
nav: About|Blog|Publications|Software|Photography

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cxhernandez.com" # the base hostname & protocol for your site
threads_username: cxhrndz
github_username:  cxhernandez
linkedin_username: carlos-xavier-hernández

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: "jsdjfaksfkas"

kramdown:
    input: GFM
    syntax_highlighter: pygments
