name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: _scripts/environment.yml
          activate-environment: cv_pdf
          auto-activate-base: false

      - name: Fetch publications from Google Scholar
        shell: bash -el {0}
        run: python ./_scripts/gscrawler.py -u 6j85aJMAAAAJ -o ./_includes/publications.md
        continue-on-error: true

      - name: Generate CV PDF
        shell: bash -el {0}
        run: python ./_scripts/generate_cv_pdf.py

      - name: Build the site in the jekyll/builder container
      - uses: actions/checkout@v4
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-1

      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync _site/ s3://cxhernandez.com \
      #       --delete \
      #       --cache-control "max-age=300" \
      #       --exclude "static/*"
      #     aws s3 sync _site/static/ s3://cxhernandez.com/static/ \
      #       --cache-control "max-age=6000"
